pdm run python src/generate.py \
--tts_device "cuda:2" \
--hifigan_device "cuda:3" \
--dataset_path ../data/train-clean-aligned \
--checkpoint_path models/priors-new.ckpt \
--output_path ../Data/synth/final_final \
--random_speaker True \
--filter_speakers 900 \
--prior_sampling "speaker_uniform" \
--batch_size 3 \
--augment True
