pdm run python litfass/generate.py \
--checkpoint_path "models/icassp_priors_dvector.ckpt" \
--dataset "../data/train-clean-b" \
--output_path "../generated/delphi" \
--hours 10.0 \
--batch_size 1 \
--use_voicefixer True \
--cache_path "../dataset_cache" \
--tts_device "cuda:0" \
--hifigan_device "cuda:1" \
--min_samples_per_speaker 50